//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShutDownRestartLockLogOff
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public long Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<long> CredentialId { get; set; }
        public Nullable<System.DateTime> DateSold { get; set; }
    }
}
